#!/bin/bash

if [[ ! -f CNAME ]]; then
    echo "Must be in the root of the repository"
    exit 1
fi

if [[ $# -ne 2 ]]; then
    echo "usage: $0 course post_name"
    exit 1
fi

COURSES=$( \
      cat _includes/courses-list.html   \
    | grep -Eo '\[[A-Z]+ [0-9][A-Z]+\]' \
    | sed 's/\[//'                      \
    | sed 's/\]//'                      \
)

COURSE=$(echo $1 | tr "[:lower:]" "[:upper:]") 
COURSE_TAG=$(echo ${COURSE%% *} | tr "[:upper:]" "[:lower:]")
while IFS= read -r c; do
    if [[ $c == ${COURSE}* ]]; then
        COURSE=$c
        FOUND_COURSE=true
        break
    fi
done <<< "$COURSES"
if [ -z ${FOUND_COURSE+0} ]; then
    if [[ $COURSE == "SVI" || $COURSE == "ALL" ]]; then
        COURSE="Svi"
        COURSE_TAG="all" 
    else
        echo "Unknown course: $COURSE"
        echo "Known courses:"
        while IFS= read -r c; do
            echo "    - $c"
        done <<< "$COURSES"
        exit 1
    fi
fi

POST_NAME=$2
CURR_YEAR=$(date +%Y)
PREV_YEAR=$(($CURR_YEAR - 1))
DATE_TAG=$(date +%F)

POST_DIR="_posts/${PREV_YEAR}_${CURR_YEAR}"
mkdir -p $POST_DIR

POST_NAME="${POST_DIR}/${DATE_TAG}-${COURSE_TAG}-${POST_NAME}.md"
POST_TIME=$(date +"%F %T %z")

if [[ ! -f $POST_NAME ]]; then
    touch $POST_NAME
    echo "---"                  >> $POST_NAME
    echo "layout: post"         >> $POST_NAME
    echo "course: ${COURSE}"    >> $POST_NAME
    echo "title: \"???\""       >> $POST_NAME
    echo "date: ${POST_TIME}"   >> $POST_NAME
    echo "comments: false"      >> $POST_NAME
    echo "---"                  >> $POST_NAME
    echo                        >> $POST_NAME
fi

$EDITOR $POST_NAME
exit $?

